use std::process::{Command, Output};

const BIN: &str = env!("CARGO_BIN_EXE_pbs-manager");

fn run(args: &[&str]) -> Output {
    Command::new(BIN)
        .args(args)
        .output()
        .expect("run pbs-manager")
}

#[test]
fn help_and_version_are_served_by_the_cli_framework() {
    let help = run(&["--help"]);
    assert!(
        help.status.success(),
        "{}",
        String::from_utf8_lossy(&help.stderr)
    );
    let help = String::from_utf8_lossy(&help.stdout);
    assert!(help.contains("Process management daemon for pi-better-subagents"));
    assert!(help.contains("completion"));
    assert!(help.contains("list"));
    assert!(
        help.contains("ls"),
        "the list alias should be discoverable: {help}"
    );
    let status_at = help
        .find("\n  status")
        .expect("status command in help");
    let daemon_at = help
        .find("\n  daemon")
        .expect("daemon command in help");
    assert!(
        status_at < daemon_at,
        "commands should follow the docs quick-reference order: {help}"
    );
    assert!(
        !help.contains("goneSessionRetention"),
        "top-level help should stay short; details belong on subcommand --help: {help}"
    );
    let daemon_help = run(&["daemon", "--help"]);
    assert!(
        daemon_help.status.success(),
        "{}",
        String::from_utf8_lossy(&daemon_help.stderr)
    );
    assert!(
        !String::from_utf8_lossy(&daemon_help.stdout).contains("--handover"),
        "internal flags stay hidden"
    );

    let subcommand_help = run(&["help", "list"]);
    assert!(subcommand_help.status.success());
    assert!(String::from_utf8_lossy(&subcommand_help.stdout).contains("--all"));

    let version = run(&["--version"]);
    assert!(version.status.success());
    let expected_prefix = format!("pbs-manager {}+", env!("CARGO_PKG_VERSION"));
    assert!(String::from_utf8_lossy(&version.stdout).starts_with(&expected_prefix));
}

#[test]
fn generated_completion_script_is_available() {
    let output = run(&["completion", "--shell", "fish"]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stdout).starts_with("# @generated by usage-argv"));

    let unsupported = run(&["completion", "--shell", "powershell"]);
    assert_eq!(
        unsupported.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&unsupported.stdout),
        String::from_utf8_lossy(&unsupported.stderr)
    );
}

#[test]
fn subcommands_are_required_and_flags_stay_command_scoped() {
    let bare = run(&[]);
    assert_eq!(
        bare.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&bare.stdout),
        String::from_utf8_lossy(&bare.stderr)
    );

    let output = run(&["sessions", "-a"]);
    assert_eq!(
        output.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn unknown_flags_remain_errors() {
    let output = run(&["list", "--definitely-unknown"]);
    assert_eq!(
        output.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stderr).contains("--definitely-unknown"));
}
