use std::process::{Command, Output};

const BIN: &str = env!("CARGO_BIN_EXE_pbs-manager");

fn run(args: &[&str]) -> Output {
    Command::new(BIN)
        .args(args)
        .output()
        .expect("run pbs-manager")
}

/// Body of one help section, from the heading through the blank line before the next.
fn help_section<'a>(help: &'a str, heading: &str) -> &'a str {
    let marker = format!("\n{heading}:\n");
    let start = help
        .find(&marker)
        .unwrap_or_else(|| panic!("{heading} missing from help:\n{help}"));
    let body = &help[start + marker.len()..];
    let end = body.find("\n\n").unwrap_or(body.len());
    &body[..end]
}

fn section_has_command(section: &str, name: &str) -> bool {
    section.lines().any(|line| {
        let rest = line.trim_start().strip_prefix(name);
        rest.is_some_and(|rest| rest.is_empty() || rest.starts_with(|c: char| c.is_whitespace()))
    })
}

#[test]
fn help_and_version_are_served_by_the_cli_framework() {
    let help = run(&["--help"]);
    assert!(
        help.status.success(),
        "{}",
        String::from_utf8_lossy(&help.stderr)
    );
    let help = String::from_utf8_lossy(&help.stdout);
    assert!(help.contains("Process management daemon for pi-better-subagents"));
    assert!(help.contains("completion"));
    assert!(help.contains("list"));
    assert!(
        help.contains("ls"),
        "the list alias should be discoverable: {help}"
    );
    let commands = help_section(&help, "Commands");
    let inspection = help_section(&help, "Inspection");
    let acting = help_section(&help, "Acting on tasks");
    let daemon = help_section(&help, "Daemon");
    assert!(
        commands.contains("completion") && commands.contains("help"),
        "ungrouped commands stay with the built-in help: {help}"
    );
    for name in ["status", "sessions", "list", "show", "agent", "events", "log", "tail", "doctor"]
    {
        assert!(
            section_has_command(inspection, name),
            "{name} should be under Inspection: {help}"
        );
    }
    for name in ["output", "wait", "stop", "kill-session", "start"] {
        assert!(
            section_has_command(acting, name),
            "{name} should be under Acting on tasks: {help}"
        );
    }
    for name in ["shutdown", "upgrade", "daemon"] {
        assert!(
            section_has_command(daemon, name),
            "{name} should be under Daemon: {help}"
        );
    }
    let status_at = inspection.find("status").expect("status");
    let doctor_at = inspection.find("doctor").expect("doctor");
    assert!(status_at < doctor_at, "inspection order: {help}");
    assert!(
        help.find("\nCommands:\n").unwrap()
            < help.find("\nInspection:\n").unwrap()
            && help.find("\nInspection:\n").unwrap() < help.find("\nActing on tasks:\n").unwrap()
            && help.find("\nActing on tasks:\n").unwrap() < help.find("\nDaemon:\n").unwrap(),
        "section order: {help}"
    );
    assert!(
        !help.contains("goneSessionRetention"),
        "top-level help should stay short; details belong on subcommand --help: {help}"
    );
    let daemon_help = run(&["daemon", "--help"]);
    assert!(
        daemon_help.status.success(),
        "{}",
        String::from_utf8_lossy(&daemon_help.stderr)
    );
    assert!(
        !String::from_utf8_lossy(&daemon_help.stdout).contains("--handover"),
        "internal flags stay hidden"
    );

    let subcommand_help = run(&["help", "list"]);
    assert!(subcommand_help.status.success());
    assert!(String::from_utf8_lossy(&subcommand_help.stdout).contains("--all"));

    let version = run(&["--version"]);
    assert!(version.status.success());
    let expected_prefix = format!("pbs-manager {}+", env!("CARGO_PKG_VERSION"));
    assert!(String::from_utf8_lossy(&version.stdout).starts_with(&expected_prefix));
}

#[test]
fn generated_completion_script_is_available() {
    let output = run(&["completion", "--shell", "fish"]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stdout).starts_with("# @generated by usage-argv"));

    let unsupported = run(&["completion", "--shell", "powershell"]);
    assert_eq!(
        unsupported.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&unsupported.stdout),
        String::from_utf8_lossy(&unsupported.stderr)
    );
}

#[test]
fn subcommands_are_required_and_flags_stay_command_scoped() {
    let bare = run(&[]);
    assert_eq!(
        bare.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&bare.stdout),
        String::from_utf8_lossy(&bare.stderr)
    );

    let output = run(&["sessions", "-a"]);
    assert_eq!(
        output.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn unknown_flags_remain_errors() {
    let output = run(&["list", "--definitely-unknown"]);
    assert_eq!(
        output.status.code(),
        Some(2),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stderr).contains("--definitely-unknown"));
}
